apiVersion: v1
kind: Service
metadata:
  name: mindmap-service
spec:
  selector:
    app: mindmap
  ports:
    - name: frontend
      port: 80
      targetPort: 5173
      protocol: TCP
    - name: backend
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mindmap-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindmap
spec:
  selector:
    matchLabels:
      app: mindmap
  replicas: 1
  template:
    metadata:
      labels:
        app: mindmap
    spec:
      containers:
        - name: be
          image: jedich/mindmap-backend
          imagePullPolicy: Never
          env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: key
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: mindmap-persistent-storage
              mountPath: /app/resources
        - name: fe
          image: jedich/mindmap-frontend
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
      volumes:
      - name: mindmap-persistent-storage
        persistentVolumeClaim:
          claimName: mindmap-img-claim