name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install dependencies
      run: go mod download
    - name: Build and Test
      run: go build ./... && go test ./...
    - name: Lint
      run: go fmt ./...
    - name: Verify mergeability
      uses: pazams/go-merge-check@v1.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}