name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install dependencies
      run: go mod download
    - name: Build and Test
      run: go build ./... && go test ./...
    - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest